{
  "hash": "1055a396de36a997dafe78db9dcfd2b4",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lesson 2 — Data Management (Cleaning Clinical Data)\"\nsubtitle: \"Clinical Data Analysis in R (Phase I) — Pre-course\"\nauthor: \"Neudata\"\nexecute:\n  echo: true\n  warning: false\n  message: false\nknitr:\n  opts_knit:\n    root.dir: \"../../Course_Preparation/04_Data_Management\"\n---\n\n\n\n## What this lesson is for\n\nReal clinical data is messy. Before any analysis we must **clean** it. In this\nlesson you will find and fix the common problems — duplicates, missing values,\ninconsistent labels, and impossible values — using a small set of `dplyr` verbs:\n`filter()`, `select()`, `mutate()`, `case_when()`, `group_by()` and\n`summarise()`.\n\nWe will work on the **raw** file (`clinical_data_raw.csv`), which contains\ndeliberate problems described in `Data/Data_Quality_Problems.md`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\n# Read the messy raw dataset\nraw <- read_csv(\"../Data/clinical_data_raw.csv\")\n\ndim(raw)      # note: more rows than patients, because of duplicates\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 433  20\n```\n\n\n:::\n:::\n\n\n---\n\n## 1. Look before you leap\n\nAlways inspect a new dataset first.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# How many missing values in each column?\ncolSums(is.na(raw))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    patient_id            age            sex      weight_kg      height_cm \n             0              0              0              0              0 \n           BMI        smoking    alcohol_use    systolic_bp   diastolic_bp \n             9              0             12              0              5 \n  hypertension       diabetes        glucose    cholesterol      treatment \n             0              0             22             18              0 \n      hospital admission_date  followup_date        outcome  time_to_event \n             0              0              7              0              0 \n```\n\n\n:::\n\n```{.r .cell-code}\n# How is 'sex' recorded? (look for inconsistent labels)\ntable(raw$sex)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n     f      F female Female      m      M   male   Male \n    56     64     58     59     45     52     50     49 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Quick numeric overview - watch for impossible minimums/maximums\nsummary(select(raw, age, height_cm, weight_kg, BMI, systolic_bp, glucose, cholesterol))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      age           height_cm       weight_kg           BMI         \n Min.   :  2.00   Min.   : 17.0   Min.   : 33.20   Min.   :   4.20  \n 1st Qu.: 46.00   1st Qu.:157.0   1st Qu.: 61.10   1st Qu.:  23.40  \n Median : 54.00   Median :163.0   Median : 70.30   Median :  26.70  \n Mean   : 54.49   Mean   :162.9   Mean   : 71.83   Mean   :  31.04  \n 3rd Qu.: 63.00   3rd Qu.:169.0   3rd Qu.: 80.80   3rd Qu.:  29.62  \n Max.   :219.00   Max.   :187.0   Max.   :400.00   Max.   :1920.40  \n                                                   NAs    :9        \n  systolic_bp       glucose        cholesterol    \n Min.   : 90.0   Min.   : 3.500   Min.   :-3.000  \n 1st Qu.:113.0   1st Qu.: 5.000   1st Qu.: 3.900  \n Median :124.0   Median : 5.500   Median : 4.600  \n Mean   :124.9   Mean   : 5.925   Mean   : 4.544  \n 3rd Qu.:135.0   3rd Qu.: 6.000   3rd Qu.: 5.100  \n Max.   :350.0   Max.   :41.000   Max.   : 7.800  \n                 NAs    :22       NAs    :18      \n```\n\n\n:::\n:::\n\n\nYou should see: several missing values, `sex` spelled many different ways, and\nsome impossible numbers (an age of 219, a height of 17 cm, a glucose of 41).\n\n## 2. Remove duplicate records\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# How many exact duplicate rows?\nsum(duplicated(raw))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3\n```\n\n\n:::\n\n```{.r .cell-code}\n# Keep only unique rows\nclean <- raw %>% distinct()\n\nnrow(clean)   # should now be 430 unique patients\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 430\n```\n\n\n:::\n:::\n\n\n## 3. Make categories consistent with `case_when()`\n\n`case_when()` reads like a set of clinical rules: *if this, then that*.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclean <- clean %>%\n  mutate(\n    # Collapse all the spellings of sex into two clean labels\n    sex = case_when(\n      sex %in% c(\"Female\", \"female\", \"F\", \"f\") ~ \"Female\",\n      sex %in% c(\"Male\", \"male\", \"M\", \"m\")     ~ \"Male\"\n    ),\n    # Standardise Yes/No variables (they were mixed with 1/0 and yes/no)\n    hypertension = case_when(\n      hypertension %in% c(\"Yes\", \"yes\", \"1\") ~ \"Yes\",\n      hypertension %in% c(\"No\",  \"no\",  \"0\") ~ \"No\"\n    ),\n    diabetes = case_when(\n      diabetes %in% c(\"Yes\", \"yes\", \"1\") ~ \"Yes\",\n      diabetes %in% c(\"No\",  \"no\",  \"0\") ~ \"No\"\n    ),\n    # Fix the stray lower-case \"current\"\n    smoking = case_when(\n      smoking %in% c(\"Current\", \"current\") ~ \"Current\",\n      TRUE ~ smoking      # keep Never / Former unchanged\n    )\n  )\n\ntable(clean$sex)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nFemale   Male \n   235    195 \n```\n\n\n:::\n\n```{.r .cell-code}\ntable(clean$hypertension)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n No Yes \n275 155 \n```\n\n\n:::\n:::\n\n\n## 4. Deal with impossible values\n\nWe cannot know the true value of an impossible entry, so we set it to `NA`.\n`if_else()` says: *if the condition is true, use the first value, otherwise the\nsecond.*\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclean <- clean %>%\n  mutate(\n    age         = if_else(age < 18 | age > 110, NA_real_, age),\n    height_cm   = if_else(height_cm < 100 | height_cm > 220, NA_real_, height_cm),\n    weight_kg   = if_else(weight_kg < 30 | weight_kg > 250, NA_real_, weight_kg),\n    systolic_bp = if_else(systolic_bp > 260, NA_real_, systolic_bp),\n    glucose     = if_else(glucose > 30, NA_real_, glucose),      # impossible fasting glucose\n    cholesterol = if_else(cholesterol < 1, NA_real_, cholesterol) # negative lab value\n  )\n\n# Recompute BMI from the cleaned weight and height so it is consistent\nclean <- clean %>%\n  mutate(BMI = round(weight_kg / (height_cm / 100)^2, 1))\n\nsummary(select(clean, age, height_cm, weight_kg, BMI, systolic_bp, glucose))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      age          height_cm       weight_kg           BMI       \n Min.   :30.00   Min.   :140.0   Min.   : 33.20   Min.   :16.00  \n 1st Qu.:46.00   1st Qu.:157.0   1st Qu.: 61.00   1st Qu.:23.40  \n Median :54.00   Median :163.0   Median : 70.20   Median :26.60  \n Mean   :54.27   Mean   :163.3   Mean   : 70.99   Mean   :26.57  \n 3rd Qu.:63.00   3rd Qu.:169.0   3rd Qu.: 80.50   3rd Qu.:29.60  \n Max.   :88.00   Max.   :187.0   Max.   :119.50   Max.   :39.20  \n NAs    :2       NAs    :1       NAs    :1        NAs    :2      \n  systolic_bp       glucose      \n Min.   : 90.0   Min.   : 3.500  \n 1st Qu.:113.0   1st Qu.: 5.000  \n Median :123.0   Median : 5.500  \n Mean   :124.3   Mean   : 5.831  \n 3rd Qu.:134.0   3rd Qu.: 6.000  \n Max.   :170.0   Max.   :13.100  \n NAs    :1       NAs    :23      \n```\n\n\n:::\n:::\n\n\nThe impossible minimums and maximums are gone.\n\n## 5. Fix the date inconsistency\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# A follow-up date should never be before the admission date\nsum(clean$followup_date < clean$admission_date, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2\n```\n\n\n:::\n\n```{.r .cell-code}\nclean <- clean %>%\n  mutate(followup_date = if_else(followup_date < admission_date,\n                                 as.Date(NA), followup_date))\n```\n:::\n\n\n## 6. Create new (derived) variables\n\nAnalysis often needs grouped or calculated variables. Here we build three.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclean <- clean %>%\n  mutate(\n    # Clinical BMI categories\n    bmi_group = case_when(\n      BMI < 18.5             ~ \"Underweight\",\n      BMI < 25               ~ \"Normal\",\n      BMI < 30               ~ \"Overweight\",\n      BMI >= 30              ~ \"Obese\"\n      # note: leaving out a \"TRUE ~\" line means missing BMI stays NA\n    ),\n    # Age groups\n    age_group = case_when(\n      age < 40               ~ \"<40\",\n      age < 55               ~ \"40-54\",\n      age < 70               ~ \"55-69\",\n      age >= 70              ~ \"70+\"\n    ),\n    # A derived clinical measure: pulse pressure\n    pulse_pressure = systolic_bp - diastolic_bp\n  )\n\ntable(clean$bmi_group)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n     Normal       Obese  Overweight Underweight \n        148          93         175          12 \n```\n\n\n:::\n\n```{.r .cell-code}\ntable(clean$age_group)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  <40 40-54 55-69   70+ \n   55   160   169    44 \n```\n\n\n:::\n:::\n\n\n## 7. The core `dplyr` verbs\n\nThese six verbs cover most day-to-day data work.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# filter(): keep rows that meet a condition\nhypertensive <- clean %>% filter(hypertension == \"Yes\")\nnrow(hypertensive)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 155\n```\n\n\n:::\n\n```{.r .cell-code}\n# select(): keep only certain columns\nsmall <- clean %>% select(patient_id, age, sex, BMI, hypertension)\nhead(small)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  patient_id   age sex      BMI hypertension\n  <chr>      <dbl> <chr>  <dbl> <chr>       \n1 P1415         49 Male    30.4 No          \n2 P1168         71 Female  25.5 No          \n3 P1371         67 Male    24.6 Yes         \n4 P1281         52 Female  29.1 Yes         \n5 P1280         50 Female  27.6 No          \n6 P1403         63 Female  20.5 Yes         \n```\n\n\n:::\n\n```{.r .cell-code}\n# group_by() + summarise(): summary statistics by group\nclean %>%\n  group_by(sex) %>%\n  summarise(\n    n           = n(),\n    mean_age    = mean(age, na.rm = TRUE),\n    mean_sbp    = mean(systolic_bp, na.rm = TRUE)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 4\n  sex        n mean_age mean_sbp\n  <chr>  <int>    <dbl>    <dbl>\n1 Female   235     54.1     124.\n2 Male     195     54.4     125.\n```\n\n\n:::\n:::\n\n\n## 8. Save the analysis-ready dataset\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Write the cleaned data so later lessons can use it\nwrite_csv(clean, \"../Data/my_clean_data.csv\")\n```\n:::\n\n\n> A ready-made reference version is already provided as\n> `Data/clinical_data_clean.csv`. From Lesson 3 onward we simply load that file,\n> so everyone starts from exactly the same point.\n\n---\n\n## Key points to remember\n\n- Always **inspect** first: `colSums(is.na())`, `table()`, `summary()`.\n- `distinct()` removes duplicate rows.\n- `case_when()` standardises messy categories using clinical rules.\n- Set **impossible values** to `NA` — never invent a value.\n- Recompute derived variables (like `BMI`) *after* fixing their inputs.\n- `filter()`, `select()`, `mutate()`, `group_by()`, `summarise()` are the\n  everyday verbs of data management.\n\n## Try it yourself\n\n1. After cleaning, how many patients are **current smokers**? (`table()`)\n2. Use `filter()` to keep only patients aged 60 or over. How many are there?\n3. Create a variable `high_bp` that is `\"High\"` when `systolic_bp >= 140` and\n   `\"Normal\"` otherwise, using `if_else()`.\n4. Use `group_by(hypertension)` and `summarise()` to compare mean BMI in\n   hypertensive vs non-hypertensive patients.\n",
    "supporting": [
      "lesson2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}