{
  "hash": "4d5e0f4e7deb191f2201ce88a01c1b9c",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Bài 2: Quản lý Dữ liệu (Làm sạch Dữ liệu Lâm sàng)\"\nsubtitle: \"Phân tích Dữ liệu Lâm sàng bằng R (Giai đoạn I), Trước khóa học\"\nauthor: \"Neudata\"\nexecute:\n  echo: true\n  warning: false\n  message: false\nknitr:\n  opts_knit:\n    root.dir: \"../../Course_Preparation/04_Data_Management\"\n---\n\n\n\n## Mục tiêu của bài học này\n\nDữ liệu lâm sàng thực tế thường lộn xộn. Trước khi phân tích bất cứ điều gì, chúng\nta phải **làm sạch** nó. Trong bài học này, bạn sẽ tìm và sửa những vấn đề thường\ngặp: bản ghi trùng lặp, giá trị khuyết, nhãn không nhất quán, và các giá trị bất\nkhả thi: bằng một tập nhỏ các động từ (verb) của `dplyr`: `filter()`, `select()`,\n`mutate()`, `case_when()`, `group_by()` và `summarise()`.\n\nChúng ta sẽ làm việc trên tệp **thô** (`clinical_data_raw.csv`), tệp này chứa các\nvấn đề được cố ý đưa vào, mô tả trong `Data/Data_Quality_Problems.md`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\n# Đọc bộ dữ liệu thô lộn xộn\nraw <- read_csv(\"../Data/clinical_data_raw.csv\")\n\ndim(raw)      # lưu ý: nhiều hàng hơn số bệnh nhân, vì có bản ghi trùng lặp\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 433  20\n```\n\n\n:::\n:::\n\n\n---\n\n## 1. Nhìn trước khi hành động\n\nLuôn luôn kiểm tra một bộ dữ liệu mới trước tiên.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Có bao nhiêu giá trị khuyết trong mỗi cột?\ncolSums(is.na(raw))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    patient_id            age            sex      weight_kg      height_cm \n             0              0              0              0              0 \n           BMI        smoking    alcohol_use    systolic_bp   diastolic_bp \n             9              0             12              0              5 \n  hypertension       diabetes        glucose    cholesterol      treatment \n             0              0             22             18              0 \n      hospital admission_date  followup_date        outcome  time_to_event \n             0              0              7              0              0 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Biến 'sex' được ghi như thế nào? (tìm các nhãn không nhất quán)\ntable(raw$sex)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n     f      F female Female      m      M   male   Male \n    56     64     58     59     45     52     50     49 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Tổng quan số nhanh - để ý các giá trị nhỏ nhất/lớn nhất bất khả thi\nsummary(select(raw, age, height_cm, weight_kg, BMI, systolic_bp, glucose, cholesterol))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      age           height_cm       weight_kg           BMI         \n Min.   :  2.00   Min.   : 17.0   Min.   : 33.20   Min.   :   4.20  \n 1st Qu.: 46.00   1st Qu.:157.0   1st Qu.: 61.10   1st Qu.:  23.40  \n Median : 54.00   Median :163.0   Median : 70.30   Median :  26.70  \n Mean   : 54.49   Mean   :162.9   Mean   : 71.83   Mean   :  31.04  \n 3rd Qu.: 63.00   3rd Qu.:169.0   3rd Qu.: 80.80   3rd Qu.:  29.62  \n Max.   :219.00   Max.   :187.0   Max.   :400.00   Max.   :1920.40  \n                                                   NAs    :9        \n  systolic_bp       glucose        cholesterol    \n Min.   : 90.0   Min.   : 3.500   Min.   :-3.000  \n 1st Qu.:113.0   1st Qu.: 5.000   1st Qu.: 3.900  \n Median :124.0   Median : 5.500   Median : 4.600  \n Mean   :124.9   Mean   : 5.925   Mean   : 4.544  \n 3rd Qu.:135.0   3rd Qu.: 6.000   3rd Qu.: 5.100  \n Max.   :350.0   Max.   :41.000   Max.   : 7.800  \n                 NAs    :22       NAs    :18      \n```\n\n\n:::\n:::\n\n\nBạn sẽ thấy: một số giá trị khuyết, biến `sex` được viết theo nhiều cách khác nhau,\nvà một số con số bất khả thi (tuổi 219, chiều cao 17 cm, glucose 41).\n\n## 2. Loại bỏ bản ghi trùng lặp\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Có bao nhiêu hàng trùng lặp hoàn toàn?\nsum(duplicated(raw))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3\n```\n\n\n:::\n\n```{.r .cell-code}\n# Chỉ giữ các hàng duy nhất\nclean <- raw %>% distinct()\n\nnrow(clean)   # bây giờ phải còn 430 bệnh nhân duy nhất\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 430\n```\n\n\n:::\n:::\n\n\n## 3. Làm cho các danh mục nhất quán bằng `case_when()`\n\n`case_when()` đọc giống như một tập hợp các quy tắc lâm sàng: *nếu điều này, thì điều kia*.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclean <- clean %>%\n  mutate(\n    # Gộp tất cả các cách viết của sex thành hai nhãn sạch\n    sex = case_when(\n      sex %in% c(\"Female\", \"female\", \"F\", \"f\") ~ \"Female\",\n      sex %in% c(\"Male\", \"male\", \"M\", \"m\")     ~ \"Male\"\n    ),\n    # Chuẩn hóa các biến Yes/No (chúng bị lẫn với 1/0 và yes/no)\n    hypertension = case_when(\n      hypertension %in% c(\"Yes\", \"yes\", \"1\") ~ \"Yes\",\n      hypertension %in% c(\"No\",  \"no\",  \"0\") ~ \"No\"\n    ),\n    diabetes = case_when(\n      diabetes %in% c(\"Yes\", \"yes\", \"1\") ~ \"Yes\",\n      diabetes %in% c(\"No\",  \"no\",  \"0\") ~ \"No\"\n    ),\n    # Sửa chữ \"current\" viết thường bị lạc\n    smoking = case_when(\n      smoking %in% c(\"Current\", \"current\") ~ \"Current\",\n      TRUE ~ smoking      # giữ nguyên Never / Former\n    )\n  )\n\ntable(clean$sex)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nFemale   Male \n   235    195 \n```\n\n\n:::\n\n```{.r .cell-code}\ntable(clean$hypertension)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n No Yes \n275 155 \n```\n\n\n:::\n:::\n\n\n## 4. Xử lý các giá trị bất khả thi\n\nChúng ta không thể biết giá trị thực của một mục nhập bất khả thi, nên ta đặt nó\nthành `NA`. `if_else()` nói rằng: *nếu điều kiện đúng, dùng giá trị thứ nhất, nếu\nkhông thì dùng giá trị thứ hai.*\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclean <- clean %>%\n  mutate(\n    age         = if_else(age < 18 | age > 110, NA_real_, age),\n    height_cm   = if_else(height_cm < 100 | height_cm > 220, NA_real_, height_cm),\n    weight_kg   = if_else(weight_kg < 30 | weight_kg > 250, NA_real_, weight_kg),\n    systolic_bp = if_else(systolic_bp > 260, NA_real_, systolic_bp),\n    glucose     = if_else(glucose > 30, NA_real_, glucose),      # glucose lúc đói bất khả thi\n    cholesterol = if_else(cholesterol < 1, NA_real_, cholesterol) # giá trị xét nghiệm âm\n  )\n\n# Tính lại BMI từ cân nặng và chiều cao đã làm sạch để nó nhất quán\nclean <- clean %>%\n  mutate(BMI = round(weight_kg / (height_cm / 100)^2, 1))\n\nsummary(select(clean, age, height_cm, weight_kg, BMI, systolic_bp, glucose))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      age          height_cm       weight_kg           BMI       \n Min.   :30.00   Min.   :140.0   Min.   : 33.20   Min.   :16.00  \n 1st Qu.:46.00   1st Qu.:157.0   1st Qu.: 61.00   1st Qu.:23.40  \n Median :54.00   Median :163.0   Median : 70.20   Median :26.60  \n Mean   :54.27   Mean   :163.3   Mean   : 70.99   Mean   :26.57  \n 3rd Qu.:63.00   3rd Qu.:169.0   3rd Qu.: 80.50   3rd Qu.:29.60  \n Max.   :88.00   Max.   :187.0   Max.   :119.50   Max.   :39.20  \n NAs    :2       NAs    :1       NAs    :1        NAs    :2      \n  systolic_bp       glucose      \n Min.   : 90.0   Min.   : 3.500  \n 1st Qu.:113.0   1st Qu.: 5.000  \n Median :123.0   Median : 5.500  \n Mean   :124.3   Mean   : 5.831  \n 3rd Qu.:134.0   3rd Qu.: 6.000  \n Max.   :170.0   Max.   :13.100  \n NAs    :1       NAs    :23      \n```\n\n\n:::\n:::\n\n\nCác giá trị nhỏ nhất và lớn nhất bất khả thi đã biến mất.\n\n## 5. Sửa sự không nhất quán về ngày tháng\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Ngày tái khám không bao giờ được trước ngày nhập viện\nsum(clean$followup_date < clean$admission_date, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2\n```\n\n\n:::\n\n```{.r .cell-code}\nclean <- clean %>%\n  mutate(followup_date = if_else(followup_date < admission_date,\n                                 as.Date(NA), followup_date))\n```\n:::\n\n\n## 6. Tạo các biến mới (biến dẫn xuất)\n\nPhân tích thường cần các biến được nhóm hoặc được tính toán. Ở đây chúng ta xây\ndựng ba biến.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclean <- clean %>%\n  mutate(\n    # Phân nhóm BMI lâm sàng\n    bmi_group = case_when(\n      BMI < 18.5             ~ \"Underweight\",\n      BMI < 25               ~ \"Normal\",\n      BMI < 30               ~ \"Overweight\",\n      BMI >= 30              ~ \"Obese\"\n      # lưu ý: bỏ dòng \"TRUE ~\" nghĩa là BMI khuyết vẫn giữ là NA\n    ),\n    # Nhóm tuổi\n    age_group = case_when(\n      age < 40               ~ \"<40\",\n      age < 55               ~ \"40-54\",\n      age < 70               ~ \"55-69\",\n      age >= 70              ~ \"70+\"\n    ),\n    # Một chỉ số lâm sàng dẫn xuất: áp lực mạch (pulse pressure)\n    pulse_pressure = systolic_bp - diastolic_bp\n  )\n\ntable(clean$bmi_group)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n     Normal       Obese  Overweight Underweight \n        148          93         175          12 \n```\n\n\n:::\n\n```{.r .cell-code}\ntable(clean$age_group)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  <40 40-54 55-69   70+ \n   55   160   169    44 \n```\n\n\n:::\n:::\n\n\n## 7. Các động từ cốt lõi của `dplyr`\n\nSáu động từ này bao quát hầu hết công việc dữ liệu hằng ngày.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# filter(): giữ các hàng thỏa mãn một điều kiện\nhypertensive <- clean %>% filter(hypertension == \"Yes\")\nnrow(hypertensive)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 155\n```\n\n\n:::\n\n```{.r .cell-code}\n# select(): chỉ giữ một số cột nhất định\nsmall <- clean %>% select(patient_id, age, sex, BMI, hypertension)\nhead(small)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  patient_id   age sex      BMI hypertension\n  <chr>      <dbl> <chr>  <dbl> <chr>       \n1 P1415         49 Male    30.4 No          \n2 P1168         71 Female  25.5 No          \n3 P1371         67 Male    24.6 Yes         \n4 P1281         52 Female  29.1 Yes         \n5 P1280         50 Female  27.6 No          \n6 P1403         63 Female  20.5 Yes         \n```\n\n\n:::\n\n```{.r .cell-code}\n# group_by() + summarise(): thống kê tóm tắt theo nhóm\nclean %>%\n  group_by(sex) %>%\n  summarise(\n    n           = n(),\n    mean_age    = mean(age, na.rm = TRUE),\n    mean_sbp    = mean(systolic_bp, na.rm = TRUE)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 4\n  sex        n mean_age mean_sbp\n  <chr>  <int>    <dbl>    <dbl>\n1 Female   235     54.1     124.\n2 Male     195     54.4     125.\n```\n\n\n:::\n:::\n\n\n## 8. Lưu bộ dữ liệu sẵn sàng để phân tích\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Ghi dữ liệu đã làm sạch để các bài học sau có thể dùng\nwrite_csv(clean, \"../Data/my_clean_data.csv\")\n```\n:::\n\n\n> Một phiên bản tham chiếu làm sẵn đã được cung cấp dưới dạng\n> `Data/clinical_data_clean.csv`. Từ Bài 3 trở đi, chúng ta chỉ đơn giản nạp tệp\n> đó, nên mọi người đều bắt đầu từ đúng cùng một điểm.\n\n---\n\n## Những điểm chính cần ghi nhớ\n\n- Luôn **kiểm tra** trước tiên: `colSums(is.na())`, `table()`, `summary()`.\n- `distinct()` loại bỏ các hàng trùng lặp.\n- `case_when()` chuẩn hóa các danh mục lộn xộn bằng các quy tắc lâm sàng.\n- Đặt **giá trị bất khả thi** thành `NA`, không bao giờ bịa ra một giá trị.\n- Tính lại các biến dẫn xuất (như `BMI`) *sau khi* đã sửa các biến đầu vào của chúng.\n- `filter()`, `select()`, `mutate()`, `group_by()`, `summarise()` là những động từ\n  hằng ngày của việc quản lý dữ liệu.\n\n## Tự thực hành\n\n1. Sau khi làm sạch, có bao nhiêu bệnh nhân **đang hút thuốc**? (`table()`)\n2. Dùng `filter()` để chỉ giữ các bệnh nhân từ 60 tuổi trở lên. Có bao nhiêu người?\n3. Tạo một biến `high_bp` bằng `\"High\"` khi `systolic_bp >= 140` và `\"Normal\"`\n   trong các trường hợp còn lại, sử dụng `if_else()`.\n4. Dùng `group_by(hypertension)` và `summarise()` để so sánh BMI trung bình ở nhóm\n   bệnh nhân tăng huyết áp và không tăng huyết áp.\n",
    "supporting": [
      "lesson2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}