{
  "hash": "c713bc22baa25e63e872a1c4648995be",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lesson 5 — Regression\"\nsubtitle: \"Clinical Data Analysis in R (Phase I) — Pre-course\"\nauthor: \"Neudata\"\nexecute:\n  echo: true\n  warning: false\n  message: false\nknitr:\n  opts_knit:\n    root.dir: \"../../Course_Preparation/07_Regression\"\n---\n\n\n\n## What this lesson is for\n\nRegression lets us study several predictors at once and **adjust** for\nconfounders. You will fit and interpret the two workhorses of clinical research:\n**linear regression** (for a continuous outcome) and **logistic regression**\n(for a yes/no outcome), and turn the output into a sentence you could put in a\npaper.\n\nWe write models plainly, so you can see exactly what is being estimated:\n\n```r\nmodel <- glm(hypertension ~ age + sex + BMI,\n             data = clinical_data,\n             family = binomial)\n```\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(broom)       # tidies model output\nlibrary(gtsummary)   # publication-ready model tables\n\nclinical_data <- read_csv(\"../Data/clinical_data_clean.csv\")\n```\n:::\n\n\n---\n\n## 1. Linear regression — a continuous outcome\n\n**Question:** Is **systolic BP** associated with **age** and **BMI**?\n\n**Data:** outcome `systolic_bp` (continuous); predictors `age`, `BMI` (continuous).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# lm() = linear model\nlin_model <- lm(systolic_bp ~ age + BMI, data = clinical_data)\nsummary(lin_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = systolic_bp ~ age + BMI, data = clinical_data)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-30.475  -7.502  -0.442   6.923  36.093 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 64.69248    3.74478  17.275   <2e-16 ***\nage          0.59738    0.04134  14.449   <2e-16 ***\nBMI          1.02730    0.11463   8.962   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 10.68 on 427 degrees of freedom\nMultiple R-squared:  0.4126,\tAdjusted R-squared:  0.4098 \nF-statistic: 149.9 on 2 and 427 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n**Output → Interpretation:** each coefficient is the change in systolic BP per\none-unit increase in that predictor, holding the other constant.\n\n- `age`: about +0.35 mmHg for each additional year.\n- `BMI`: about +0.6 mmHg for each additional BMI unit.\n- Both p-values are very small, so both associations are statistically\n  significant.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Tidy estimates with 95% confidence intervals\ntidy(lin_model, conf.int = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 7\n  term        estimate std.error statistic  p.value conf.low conf.high\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>    <dbl>     <dbl>\n1 (Intercept)   64.7      3.74       17.3  4.32e-51   57.3      72.1  \n2 age            0.597    0.0413     14.4  8.28e-39    0.516     0.679\n3 BMI            1.03     0.115       8.96 1.00e-17    0.802     1.25 \n```\n\n\n:::\n:::\n\n\n**Reporting:** *\"Each additional year of age was associated with a 0.35 mmHg\nhigher systolic BP (95% CI ...), and each BMI unit with a 0.62 mmHg increase,\nafter mutual adjustment.\"*\n\n## 2. Logistic regression — a yes/no outcome\n\nWhen the outcome is binary (Yes/No), we use **logistic regression**, which gives\n**odds ratios (OR)**.\n\n**Question:** What is associated with **having hypertension**?\n\n**Data:** outcome `hypertension` (Yes/No); predictors `age`, `sex`, `BMI`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Make hypertension a factor with \"No\" as the reference level\nclinical_data <- clinical_data %>%\n  mutate(hypertension = factor(hypertension, levels = c(\"No\", \"Yes\")))\n\n# glm() with family = binomial fits a logistic regression\nlog_model <- glm(hypertension ~ age + sex + BMI,\n                 data = clinical_data,\n                 family = binomial)\n\nsummary(log_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = hypertension ~ age + sex + BMI, family = binomial, \n    data = clinical_data)\n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)    \n(Intercept) -9.60637    1.09092  -8.806  < 2e-16 ***\nage          0.08980    0.01134   7.918 2.42e-15 ***\nsexMale      0.18264    0.23225   0.786    0.432    \nBMI          0.14702    0.02766   5.316 1.06e-07 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 562.17  on 429  degrees of freedom\nResidual deviance: 446.64  on 426  degrees of freedom\nAIC: 454.64\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n:::\n\n\nThe `summary()` output is on the **log-odds** scale — hard to read. We convert to\n**odds ratios** by exponentiating.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# exponentiate = TRUE turns log-odds into odds ratios\ntidy(log_model, exponentiate = TRUE, conf.int = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 7\n  term         estimate std.error statistic  p.value   conf.low conf.high\n  <chr>           <dbl>     <dbl>     <dbl>    <dbl>      <dbl>     <dbl>\n1 (Intercept) 0.0000673    1.09      -8.81  1.30e-18 0.00000719  0.000523\n2 age         1.09         0.0113     7.92  2.42e-15 1.07        1.12    \n3 sexMale     1.20         0.232      0.786 4.32e- 1 0.761       1.90    \n4 BMI         1.16         0.0277     5.32  1.06e- 7 1.10        1.22    \n```\n\n\n:::\n:::\n\n\n**Output → Interpretation (odds ratios):**\n\n- `age`: OR ≈ **1.09** — each extra year raises the odds of hypertension by ~9%.\n- `BMI`: OR ≈ **1.16** — each extra BMI unit raises the odds by ~16%.\n- `sex (Male)`: OR ≈ **1.20**, but the confidence interval crosses 1 and p ≈ 0.43\n  — **no evidence** of a sex difference.\n\nAn OR **above 1** means higher odds; **below 1** means lower odds; a CI that\n**includes 1** means \"not statistically significant\".\n\n## 3. A publication-ready regression table\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntbl_regression(log_model, exponentiate = TRUE)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"plqvnyfkdp\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#plqvnyfkdp table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#plqvnyfkdp thead, #plqvnyfkdp tbody, #plqvnyfkdp tfoot, #plqvnyfkdp tr, #plqvnyfkdp td, #plqvnyfkdp th {\n  border-style: none;\n}\n\n#plqvnyfkdp p {\n  margin: 0;\n  padding: 0;\n}\n\n#plqvnyfkdp .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#plqvnyfkdp .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#plqvnyfkdp .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#plqvnyfkdp .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#plqvnyfkdp .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#plqvnyfkdp .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#plqvnyfkdp .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#plqvnyfkdp .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#plqvnyfkdp .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#plqvnyfkdp .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#plqvnyfkdp .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#plqvnyfkdp .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#plqvnyfkdp .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#plqvnyfkdp .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#plqvnyfkdp .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#plqvnyfkdp .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#plqvnyfkdp .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#plqvnyfkdp .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#plqvnyfkdp .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#plqvnyfkdp .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#plqvnyfkdp .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#plqvnyfkdp .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#plqvnyfkdp .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#plqvnyfkdp .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#plqvnyfkdp .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#plqvnyfkdp .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#plqvnyfkdp .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#plqvnyfkdp .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#plqvnyfkdp .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#plqvnyfkdp .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#plqvnyfkdp .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#plqvnyfkdp .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#plqvnyfkdp .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#plqvnyfkdp .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#plqvnyfkdp .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#plqvnyfkdp .gt_left {\n  text-align: left;\n}\n\n#plqvnyfkdp .gt_center {\n  text-align: center;\n}\n\n#plqvnyfkdp .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#plqvnyfkdp .gt_font_normal {\n  font-weight: normal;\n}\n\n#plqvnyfkdp .gt_font_bold {\n  font-weight: bold;\n}\n\n#plqvnyfkdp .gt_font_italic {\n  font-style: italic;\n}\n\n#plqvnyfkdp .gt_super {\n  font-size: 65%;\n}\n\n#plqvnyfkdp .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#plqvnyfkdp .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#plqvnyfkdp .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#plqvnyfkdp .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#plqvnyfkdp .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#plqvnyfkdp .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#plqvnyfkdp .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#plqvnyfkdp .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#plqvnyfkdp div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"label\"><span data-qmd-base64=\"KipDaGFyYWN0ZXJpc3RpYyoq\"><span class='gt_from_md'><strong>Characteristic</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\"><span data-qmd-base64=\"KipPUioq\"><span class='gt_from_md'><strong>OR</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\"><span data-qmd-base64=\"Kio5NSUgQ0kqKg==\"><span class='gt_from_md'><strong>95% CI</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\"><span data-qmd-base64=\"KipwLXZhbHVlKio=\"><span class='gt_from_md'><strong>p-value</strong></span></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">age</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">1.09</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">1.07, 1.12</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">sex</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Female</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">—</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">—</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Male</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">1.20</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">0.76, 1.90</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.4</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">BMI</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">1.16</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">1.10, 1.22</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n  </tbody>\n  <tfoot>\n    <tr class=\"gt_sourcenotes\">\n      <td class=\"gt_sourcenote\" colspan=\"4\"><span data-qmd-base64=\"QWJicmV2aWF0aW9uczogQ0kgPSBDb25maWRlbmNlIEludGVydmFsLCBPUiA9IE9kZHMgUmF0aW8=\"><span class='gt_from_md'>Abbreviations: CI = Confidence Interval, OR = Odds Ratio</span></span></td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\nThis is the table format journals expect: each predictor with its OR, 95% CI and\np-value.\n\n## 4. Adjustment and confounding (why regression matters)\n\nOlder patients tend to have higher BMI *and* more hypertension. A simple\ncomparison could mistake age's effect for BMI's. Putting both in the same model\n**adjusts** each for the other, so each odds ratio is \"independent of\" the other\npredictors. This is the core reason clinical research uses multivariable models.\n\n---\n\n## Key points to remember\n\n- **Linear regression** (`lm`) — continuous outcome; coefficients are changes in\n  the outcome per unit of predictor.\n- **Logistic regression** (`glm(..., family = binomial)`) — binary outcome;\n  exponentiated coefficients are **odds ratios**.\n- `tidy(model, exponentiate = TRUE, conf.int = TRUE)` gives OR + 95% CI.\n- OR > 1 raises the odds, < 1 lowers it; a CI crossing 1 is non-significant.\n- Multivariable models **adjust** for confounders — the main reason we use them.\n- Report the estimate and its confidence interval in words, never raw output.\n\n## Try it yourself\n\n1. Fit `lm(diastolic_bp ~ age + BMI)`. How much does diastolic BP change per BMI\n   unit?\n2. Fit a logistic model `diabetes ~ age + BMI`. Report the odds ratios.\n3. Add `diabetes` to the hypertension model (`hypertension ~ age + sex + BMI +\n   diabetes`). Does the OR for diabetes suggest an association?\n4. Write one publication-style sentence reporting the age and BMI odds ratios\n   from the hypertension model.\n",
    "supporting": [
      "lesson5_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}