{
  "hash": "497bed923a1489cdec9a7f80e23673fe",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Bài 5: Hồi quy\"\nsubtitle: \"Phân tích Dữ liệu Lâm sàng bằng R (Giai đoạn I), Trước khóa học\"\nauthor: \"Neudata\"\nexecute:\n  echo: true\n  warning: false\n  message: false\nknitr:\n  opts_knit:\n    root.dir: \"../../Course_Preparation/07_Regression\"\n---\n\n\n\n## Mục tiêu của bài học này\n\nHồi quy cho phép chúng ta nghiên cứu nhiều biến dự báo cùng một lúc và **hiệu chỉnh**\ncho các yếu tố nhiễu. Bạn sẽ khớp và diễn giải hai công cụ chủ lực của nghiên cứu\nlâm sàng: **hồi quy tuyến tính** (cho biến kết cục liên tục) và **hồi quy logistic**\n(cho biến kết cục có/không), rồi biến kết quả đầu ra thành một câu bạn có thể đưa vào\nmột bài báo.\n\nChúng ta viết mô hình một cách rõ ràng, để bạn có thể thấy chính xác điều gì đang\nđược ước lượng:\n\n```r\nmodel <- glm(hypertension ~ age + sex + BMI,\n             data = clinical_data,\n             family = binomial)\n```\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(broom)       # sắp xếp gọn kết quả đầu ra của mô hình\nlibrary(gtsummary)   # bảng mô hình sẵn sàng để xuất bản\n\nclinical_data <- read_csv(\"../Data/clinical_data_clean.csv\")\n```\n:::\n\n\n---\n\n## 1. Hồi quy tuyến tính: một biến kết cục liên tục\n\n**Câu hỏi:** Liệu **huyết áp tâm thu** có liên quan đến **tuổi** và **BMI** không?\n\n**Dữ liệu:** biến kết cục `systolic_bp` (liên tục); biến dự báo `age`, `BMI` (liên tục).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# lm() = linear model (mô hình tuyến tính)\nlin_model <- lm(systolic_bp ~ age + BMI, data = clinical_data)\nsummary(lin_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = systolic_bp ~ age + BMI, data = clinical_data)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-30.475  -7.502  -0.442   6.923  36.093 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 64.69248    3.74478  17.275   <2e-16 ***\nage          0.59738    0.04134  14.449   <2e-16 ***\nBMI          1.02730    0.11463   8.962   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 10.68 on 427 degrees of freedom\nMultiple R-squared:  0.4126,\tAdjusted R-squared:  0.4098 \nF-statistic: 149.9 on 2 and 427 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n**Kết quả → Diễn giải:** mỗi hệ số là mức thay đổi của huyết áp tâm thu ứng với một\nđơn vị tăng của biến dự báo đó, khi giữ cố định biến còn lại.\n\n- `age`: khoảng +0.35 mmHg cho mỗi năm tuổi tăng thêm.\n- `BMI`: khoảng +0.6 mmHg cho mỗi đơn vị BMI tăng thêm.\n- Cả hai giá trị p đều rất nhỏ, nên cả hai mối liên quan đều có ý nghĩa thống kê.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Ước lượng được sắp xếp gọn kèm khoảng tin cậy 95%\ntidy(lin_model, conf.int = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 7\n  term        estimate std.error statistic  p.value conf.low conf.high\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>    <dbl>     <dbl>\n1 (Intercept)   64.7      3.74       17.3  4.32e-51   57.3      72.1  \n2 age            0.597    0.0413     14.4  8.28e-39    0.516     0.679\n3 BMI            1.03     0.115       8.96 1.00e-17    0.802     1.25 \n```\n\n\n:::\n:::\n\n\n**Báo cáo:** *\"Mỗi năm tuổi tăng thêm có liên quan đến huyết áp tâm thu cao hơn\n0.35 mmHg (KTC 95% ...), và mỗi đơn vị BMI liên quan đến mức tăng 0.62 mmHg, sau khi\nhiệu chỉnh lẫn nhau.\"*\n\n## 2. Hồi quy logistic: một biến kết cục có/không\n\nKhi biến kết cục là nhị phân (Yes/No), chúng ta dùng **hồi quy logistic**, cho ra\n**tỷ số chênh (OR)**.\n\n**Câu hỏi:** Điều gì có liên quan đến việc **mắc tăng huyết áp**?\n\n**Dữ liệu:** biến kết cục `hypertension` (Yes/No); biến dự báo `age`, `sex`, `BMI`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Biến hypertension thành factor với \"No\" làm mức tham chiếu\nclinical_data <- clinical_data %>%\n  mutate(hypertension = factor(hypertension, levels = c(\"No\", \"Yes\")))\n\n# glm() với family = binomial khớp một hồi quy logistic\nlog_model <- glm(hypertension ~ age + sex + BMI,\n                 data = clinical_data,\n                 family = binomial)\n\nsummary(log_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = hypertension ~ age + sex + BMI, family = binomial, \n    data = clinical_data)\n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)    \n(Intercept) -9.60637    1.09092  -8.806  < 2e-16 ***\nage          0.08980    0.01134   7.918 2.42e-15 ***\nsexMale      0.18264    0.23225   0.786    0.432    \nBMI          0.14702    0.02766   5.316 1.06e-07 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 562.17  on 429  degrees of freedom\nResidual deviance: 446.64  on 426  degrees of freedom\nAIC: 454.64\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n:::\n\n\nKết quả của `summary()` nằm trên thang **log-odds (log của số chênh)**, khó đọc.\nChúng ta chuyển sang **tỷ số chênh** bằng cách lấy lũy thừa (exponentiate).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# exponentiate = TRUE biến log-odds thành tỷ số chênh\ntidy(log_model, exponentiate = TRUE, conf.int = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 7\n  term         estimate std.error statistic  p.value   conf.low conf.high\n  <chr>           <dbl>     <dbl>     <dbl>    <dbl>      <dbl>     <dbl>\n1 (Intercept) 0.0000673    1.09      -8.81  1.30e-18 0.00000719  0.000523\n2 age         1.09         0.0113     7.92  2.42e-15 1.07        1.12    \n3 sexMale     1.20         0.232      0.786 4.32e- 1 0.761       1.90    \n4 BMI         1.16         0.0277     5.32  1.06e- 7 1.10        1.22    \n```\n\n\n:::\n:::\n\n\n**Kết quả → Diễn giải (tỷ số chênh):**\n\n- `age`: OR ≈ **1.09**: mỗi năm tuổi tăng thêm làm tăng số chênh mắc tăng huyết áp\n  khoảng 9%.\n- `BMI`: OR ≈ **1.16**: mỗi đơn vị BMI tăng thêm làm tăng số chênh khoảng 16%.\n- `sex (Male)`: OR ≈ **1.20**, nhưng khoảng tin cậy vượt qua 1 và p ≈ 0.43, **không\n  có bằng chứng** về sự khác biệt giới tính.\n\nMột OR **trên 1** nghĩa là số chênh cao hơn; **dưới 1** nghĩa là số chênh thấp hơn;\nmột KTC **bao gồm 1** nghĩa là \"không có ý nghĩa thống kê\".\n\n## 3. Một bảng hồi quy sẵn sàng để xuất bản\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntbl_regression(log_model, exponentiate = TRUE)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"wsmhylyxxk\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#wsmhylyxxk table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#wsmhylyxxk thead, #wsmhylyxxk tbody, #wsmhylyxxk tfoot, #wsmhylyxxk tr, #wsmhylyxxk td, #wsmhylyxxk th {\n  border-style: none;\n}\n\n#wsmhylyxxk p {\n  margin: 0;\n  padding: 0;\n}\n\n#wsmhylyxxk .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#wsmhylyxxk .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#wsmhylyxxk .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#wsmhylyxxk .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#wsmhylyxxk .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#wsmhylyxxk .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wsmhylyxxk .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#wsmhylyxxk .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#wsmhylyxxk .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#wsmhylyxxk .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#wsmhylyxxk .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#wsmhylyxxk .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#wsmhylyxxk .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#wsmhylyxxk .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#wsmhylyxxk .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#wsmhylyxxk .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#wsmhylyxxk .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#wsmhylyxxk .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#wsmhylyxxk .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wsmhylyxxk .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#wsmhylyxxk .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#wsmhylyxxk .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#wsmhylyxxk .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wsmhylyxxk .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#wsmhylyxxk .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#wsmhylyxxk .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wsmhylyxxk .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wsmhylyxxk .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#wsmhylyxxk .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wsmhylyxxk .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#wsmhylyxxk .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wsmhylyxxk .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#wsmhylyxxk .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wsmhylyxxk .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#wsmhylyxxk .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wsmhylyxxk .gt_left {\n  text-align: left;\n}\n\n#wsmhylyxxk .gt_center {\n  text-align: center;\n}\n\n#wsmhylyxxk .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#wsmhylyxxk .gt_font_normal {\n  font-weight: normal;\n}\n\n#wsmhylyxxk .gt_font_bold {\n  font-weight: bold;\n}\n\n#wsmhylyxxk .gt_font_italic {\n  font-style: italic;\n}\n\n#wsmhylyxxk .gt_super {\n  font-size: 65%;\n}\n\n#wsmhylyxxk .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#wsmhylyxxk .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#wsmhylyxxk .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#wsmhylyxxk .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#wsmhylyxxk .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#wsmhylyxxk .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#wsmhylyxxk .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#wsmhylyxxk .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#wsmhylyxxk div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"label\"><span data-qmd-base64=\"KipDaGFyYWN0ZXJpc3RpYyoq\"><span class='gt_from_md'><strong>Characteristic</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\"><span data-qmd-base64=\"KipPUioq\"><span class='gt_from_md'><strong>OR</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\"><span data-qmd-base64=\"Kio5NSUgQ0kqKg==\"><span class='gt_from_md'><strong>95% CI</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\"><span data-qmd-base64=\"KipwLXZhbHVlKio=\"><span class='gt_from_md'><strong>p-value</strong></span></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">age</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">1.09</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">1.07, 1.12</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">sex</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Female</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">—</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">—</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Male</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">1.20</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">0.76, 1.90</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.4</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">BMI</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">1.16</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">1.10, 1.22</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n  </tbody>\n  <tfoot>\n    <tr class=\"gt_sourcenotes\">\n      <td class=\"gt_sourcenote\" colspan=\"4\"><span data-qmd-base64=\"QWJicmV2aWF0aW9uczogQ0kgPSBDb25maWRlbmNlIEludGVydmFsLCBPUiA9IE9kZHMgUmF0aW8=\"><span class='gt_from_md'>Abbreviations: CI = Confidence Interval, OR = Odds Ratio</span></span></td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\nĐây là định dạng bảng mà các tạp chí mong đợi: mỗi biến dự báo với OR, KTC 95% và\ngiá trị p của nó.\n\n## 4. Hiệu chỉnh và yếu tố nhiễu (vì sao hồi quy quan trọng)\n\nBệnh nhân lớn tuổi hơn có xu hướng có BMI cao hơn *và* nhiều tăng huyết áp hơn. Một\nso sánh đơn giản có thể nhầm tác động của tuổi thành tác động của BMI. Đưa cả hai vào\ncùng một mô hình sẽ **hiệu chỉnh** biến này theo biến kia, nên mỗi tỷ số chênh là\n\"độc lập với\" các biến dự báo còn lại. Đây là lý do cốt lõi khiến nghiên cứu lâm sàng\nsử dụng các mô hình đa biến.\n\n---\n\n## Những điểm chính cần ghi nhớ\n\n- **Hồi quy tuyến tính** (`lm`), biến kết cục liên tục; các hệ số là mức thay đổi\n  của biến kết cục ứng với một đơn vị của biến dự báo.\n- **Hồi quy logistic** (`glm(..., family = binomial)`), biến kết cục nhị phân; các\n  hệ số đã lấy lũy thừa là **tỷ số chênh**.\n- `tidy(model, exponentiate = TRUE, conf.int = TRUE)` cho OR + KTC 95%.\n- OR > 1 làm tăng số chênh, < 1 làm giảm nó; một KTC vượt qua 1 là không có ý nghĩa\n  thống kê.\n- Các mô hình đa biến **hiệu chỉnh** cho các yếu tố nhiễu, lý do chính khiến chúng\n  ta dùng chúng.\n- Báo cáo ước lượng và khoảng tin cậy của nó bằng lời, không bao giờ dùng kết quả\n  đầu ra thô.\n\n## Tự thực hành\n\n1. Khớp `lm(diastolic_bp ~ age + BMI)`. Huyết áp tâm trương thay đổi bao nhiêu cho\n   mỗi đơn vị BMI?\n2. Khớp một mô hình logistic `diabetes ~ age + BMI`. Báo cáo các tỷ số chênh.\n3. Thêm `diabetes` vào mô hình tăng huyết áp (`hypertension ~ age + sex + BMI +\n   diabetes`). Tỷ số chênh của diabetes có gợi ý một mối liên quan không?\n4. Viết một câu theo phong cách xuất bản báo cáo tỷ số chênh của tuổi và BMI từ mô\n   hình tăng huyết áp.\n",
    "supporting": [
      "lesson5_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}